### ISSUE TITLE
报错啊。。。

### ISSUE THREAD

**Issue by hellworld** [liyuanjinglyj/XiuYiXiuDemo#1]
FATAL EXCEPTION: main
                                                                                     Process: com.example.liyuanjing.xiuyixiudemo, PID: 31533
                                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.RelativeLayout.addView(android.view.View)' on a null object reference
                                                                                         at com.example.liyuanjing.xiuyixiudemo.XiuYiXiuActivity$3.run(XiuYiXiuActivity.java:109)
                                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by liyuanjinglyj** [comment]
是第一种还是第二种提示的错误？？？

**Comment by leigo** [comment]
用第二种的实现报错。`XiuYiXiuActivity.java`
